/* tslint:disable */
/* eslint-disable */
/**
 * Izi Crawler API
 * server-api-v1
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthConfirmResponseDto
 */
export interface AuthConfirmResponseDto {
    /**
     * 
     * @type {string}
     * @memberof AuthConfirmResponseDto
     */
    message: string;
}

/**
 * Check if a given object implements the AuthConfirmResponseDto interface.
 */
export function instanceOfAuthConfirmResponseDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function AuthConfirmResponseDtoFromJSON(json: any): AuthConfirmResponseDto {
    return AuthConfirmResponseDtoFromJSONTyped(json, false);
}

export function AuthConfirmResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthConfirmResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function AuthConfirmResponseDtoToJSON(value?: AuthConfirmResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

