/* tslint:disable */
/* eslint-disable */
/**
 * Izi Crawler API
 * server-api-v1
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthConfirmDto
 */
export interface AuthConfirmDto {
    /**
     * 
     * @type {string}
     * @memberof AuthConfirmDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AuthConfirmDto
     */
    confirmationCode: string;
}

/**
 * Check if a given object implements the AuthConfirmDto interface.
 */
export function instanceOfAuthConfirmDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "confirmationCode" in value;

    return isInstance;
}

export function AuthConfirmDtoFromJSON(json: any): AuthConfirmDto {
    return AuthConfirmDtoFromJSONTyped(json, false);
}

export function AuthConfirmDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthConfirmDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'confirmationCode': json['confirmationCode'],
    };
}

export function AuthConfirmDtoToJSON(value?: AuthConfirmDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'confirmationCode': value.confirmationCode,
    };
}

