/* tslint:disable */
/* eslint-disable */
/**
 * Izi Crawler API
 * server-api-v1
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthSafePasswordDto
 */
export interface AuthSafePasswordDto {
    /**
     * 
     * @type {string}
     * @memberof AuthSafePasswordDto
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof AuthSafePasswordDto
     */
    confirmPassword: string;
}

/**
 * Check if a given object implements the AuthSafePasswordDto interface.
 */
export function instanceOfAuthSafePasswordDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "confirmPassword" in value;

    return isInstance;
}

export function AuthSafePasswordDtoFromJSON(json: any): AuthSafePasswordDto {
    return AuthSafePasswordDtoFromJSONTyped(json, false);
}

export function AuthSafePasswordDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthSafePasswordDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'password': json['password'],
        'confirmPassword': json['confirmPassword'],
    };
}

export function AuthSafePasswordDtoToJSON(value?: AuthSafePasswordDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'password': value.password,
        'confirmPassword': value.confirmPassword,
    };
}

