/* tslint:disable */
/* eslint-disable */
/**
 * Izi Crawler API
 * server-api-v1
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthSignInDto
 */
export interface AuthSignInDto {
    /**
     * 
     * @type {string}
     * @memberof AuthSignInDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AuthSignInDto
     */
    password: string;
}

/**
 * Check if a given object implements the AuthSignInDto interface.
 */
export function instanceOfAuthSignInDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function AuthSignInDtoFromJSON(json: any): AuthSignInDto {
    return AuthSignInDtoFromJSONTyped(json, false);
}

export function AuthSignInDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthSignInDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function AuthSignInDtoToJSON(value?: AuthSignInDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
    };
}

