/* tslint:disable */
/* eslint-disable */
/**
 * Izi Crawler API
 * server-api-v1
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BadRequestDto
 */
export interface BadRequestDto {
    /**
     * Object containing field-specific error messages.
     * @type {object}
     * @memberof BadRequestDto
     */
    errors: object;
}

/**
 * Check if a given object implements the BadRequestDto interface.
 */
export function instanceOfBadRequestDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "errors" in value;

    return isInstance;
}

export function BadRequestDtoFromJSON(json: any): BadRequestDto {
    return BadRequestDtoFromJSONTyped(json, false);
}

export function BadRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BadRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errors': json['errors'],
    };
}

export function BadRequestDtoToJSON(value?: BadRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errors': value.errors,
    };
}

