/* tslint:disable */
/* eslint-disable */
/**
 * Izi Crawler API
 * server-api-v1
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthConfirmDto,
  AuthEmailDto,
  AuthSafePasswordDto,
  AuthSignInDto,
  AuthTokenDto,
  AuthUpdatePasswordDto,
  BadRequestDto,
} from '../models/index';
import {
    AuthConfirmDtoFromJSON,
    AuthConfirmDtoToJSON,
    AuthEmailDtoFromJSON,
    AuthEmailDtoToJSON,
    AuthSafePasswordDtoFromJSON,
    AuthSafePasswordDtoToJSON,
    AuthSignInDtoFromJSON,
    AuthSignInDtoToJSON,
    AuthTokenDtoFromJSON,
    AuthTokenDtoToJSON,
    AuthUpdatePasswordDtoFromJSON,
    AuthUpdatePasswordDtoToJSON,
    BadRequestDtoFromJSON,
    BadRequestDtoToJSON,
} from '../models/index';

export interface AuthApiConfirmAccountRequest {
    authConfirmDto: AuthConfirmDto;
}

export interface AuthApiConfirmationCodeRequest {
    authEmailDto: AuthEmailDto;
}

export interface AuthApiResetPasswordRequest {
    authSafePasswordDto: AuthSafePasswordDto;
}

export interface AuthApiSignInRequest {
    authSignInDto: AuthSignInDto;
}

export interface AuthApiSignUpRequest {
    authEmailDto: AuthEmailDto;
}

export interface AuthApiUpdatePasswordRequest {
    authUpdatePasswordDto: AuthUpdatePasswordDto;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     */
    async confirmAccountRaw(requestParameters: AuthApiConfirmAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.authConfirmDto === null || requestParameters.authConfirmDto === undefined) {
            throw new runtime.RequiredError('authConfirmDto','Required parameter requestParameters.authConfirmDto was null or undefined when calling confirmAccount.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/confirm-account`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthConfirmDtoToJSON(requestParameters.authConfirmDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async confirmAccount(authConfirmDto: AuthConfirmDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.confirmAccountRaw({ authConfirmDto: authConfirmDto }, initOverrides);
    }

    /**
     */
    async confirmationCodeRaw(requestParameters: AuthApiConfirmationCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.authEmailDto === null || requestParameters.authEmailDto === undefined) {
            throw new runtime.RequiredError('authEmailDto','Required parameter requestParameters.authEmailDto was null or undefined when calling confirmationCode.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/confirmation-code`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthEmailDtoToJSON(requestParameters.authEmailDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async confirmationCode(authEmailDto: AuthEmailDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.confirmationCodeRaw({ authEmailDto: authEmailDto }, initOverrides);
    }

    /**
     */
    async resetPasswordRaw(requestParameters: AuthApiResetPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.authSafePasswordDto === null || requestParameters.authSafePasswordDto === undefined) {
            throw new runtime.RequiredError('authSafePasswordDto','Required parameter requestParameters.authSafePasswordDto was null or undefined when calling resetPassword.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/reset-password`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthSafePasswordDtoToJSON(requestParameters.authSafePasswordDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async resetPassword(authSafePasswordDto: AuthSafePasswordDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.resetPasswordRaw({ authSafePasswordDto: authSafePasswordDto }, initOverrides);
    }

    /**
     */
    async signInRaw(requestParameters: AuthApiSignInRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthTokenDto>> {
        if (requestParameters.authSignInDto === null || requestParameters.authSignInDto === undefined) {
            throw new runtime.RequiredError('authSignInDto','Required parameter requestParameters.authSignInDto was null or undefined when calling signIn.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/sign-in`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthSignInDtoToJSON(requestParameters.authSignInDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthTokenDtoFromJSON(jsonValue));
    }

    /**
     */
    async signIn(authSignInDto: AuthSignInDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthTokenDto> {
        const response = await this.signInRaw({ authSignInDto: authSignInDto }, initOverrides);
        return await response.value();
    }

    /**
     */
    async signUpRaw(requestParameters: AuthApiSignUpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.authEmailDto === null || requestParameters.authEmailDto === undefined) {
            throw new runtime.RequiredError('authEmailDto','Required parameter requestParameters.authEmailDto was null or undefined when calling signUp.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/sign-up`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthEmailDtoToJSON(requestParameters.authEmailDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async signUp(authEmailDto: AuthEmailDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.signUpRaw({ authEmailDto: authEmailDto }, initOverrides);
    }

    /**
     */
    async updatePasswordRaw(requestParameters: AuthApiUpdatePasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.authUpdatePasswordDto === null || requestParameters.authUpdatePasswordDto === undefined) {
            throw new runtime.RequiredError('authUpdatePasswordDto','Required parameter requestParameters.authUpdatePasswordDto was null or undefined when calling updatePassword.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/update-password`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthUpdatePasswordDtoToJSON(requestParameters.authUpdatePasswordDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updatePassword(authUpdatePasswordDto: AuthUpdatePasswordDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updatePasswordRaw({ authUpdatePasswordDto: authUpdatePasswordDto }, initOverrides);
    }

}
