export const NAVIGATION_NAMES = {
    bottomTabsNavigator: 'bottom-tabs-navigator',
    crawl: 'crawl',
    crawlRouteDetails: 'crawl-route-details',
    crawlRouteMap: 'crawl-route-map',
    crawlRoutesNavigator: 'crawl-routes-navigator',
    explore: 'explore',
    favoriteRoutes: 'favorite-routes',
    home: 'home',
    login: 'login',
    myRoutes: 'my-routes',
    profile: 'profile',
    signup: 'signup',
    welcome: 'welcome',
};
