export const NAVIGATION_ROUTES = {
    confirmationCode: '/confirmation-code',
    crawl: '/crawl',
    explore: '/explore',
    favoriteRoutes: '/favorite-routes',
    home: '/',
    index: '/',
    login: '/login',
    myActivity: '/my-activity',
    myProfile: '/my-profile',
    myRoutes: '/myRoutes',
    profile: '/profile',
    route: '/route/[guid]',
    routeMap: '/route/[guid]/map',
    settings: '/settings',
    signup: '/signup',
    welcome: '/welcome',
};
