version: '3.1'

services:
    izi-crawler-builder:
        build:
            context: ./
            dockerfile: ./docker/Dockerfile
        env_file:
            - ./client-mobile-v1/.env
            - ./client-mobile-v1/.env.preview
        network_mode: 'host'
        restart: on-failure
        volumes:
            - ./client-mobile-v1:/project/app
    izi-cawler-db:
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: db
            MYSQL_USER: admin
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root_password
        ports:
            - 3306:3306
        volumes:
            - ./db-v1:/data/db
        container_name: music-game-db
        command: --default-authentication-plugin=mysql_native_password
